export const employees = [
  {
    id: '1',
    code: 'MNV-001',
    firstName: 'Nguyễn	Văn',
    lastName: 'A',
    personalEmail: 'nguyenvana01@gmail.com',
    workEmail: 'a.nguyen@base.vn',
    phone: '0984000001',
    dateOfBirth: '01/01/1996',
    sex: 'Nam',
    department: 'BOD',
    employeeType: 'BOD',
    jobTitle: 'Giám đốc',
    salary: '9000000',
    dateStarted: '01/01/2018',
    workType: 'Full-Time',
    branch: 'Cơ sở Nguyễn Tuân',
    currentAddress: 'Số 47, Quan Nhân, Thanh Xuân, Hà Nội',
    permanentAddress: 'Thanh Thuỷ, Thanh Hà, Hải Dương',
    nationalId: '142700000',
    licenseDate: '01/01/2016',
    licensePlace: 'CA Hải Dương',
  },
  {
    id: '2',
    code: 'MNV-002',
    firstName: 'Nguyễn	Văn',
    lastName: 'A',
    personalEmail: 'nguyenvana01@gmail.com',
    workEmail: 'a.nguyen@base.vn',
    phone: '0984000002',
    dateOfBirth: '02/01/1996',
    sex: 'Nam',
    department: 'Back Office',
    employeeType: 'Nhân viên',
    jobTitle: 'Thư ký giám đốc',
    salary: '9000000',
    dateStarted: '02/01/2018',
    workType: 'Full-Time',
    branch: 'Cơ sở Nguyễn Tuân',
    currentAddress: 'Số 47, Quan Nhân, Thanh Xuân, Hà Nội',
    permanentAddress: 'Thanh Thuỷ, Thanh Hà, Hải Dương',
    nationalId: '142700000',
    licenseDate: '02/01/2016',
    licensePlace: 'CA Hải Dương',
  },
  {
    id: '3',
    code: 'MNV-003',
    firstName: 'Nguyễn	Văn',
    lastName: 'A',
    personalEmail: 'nguyenvana01@gmail.com',
    workEmail: 'a.nguyen@base.vn',
    phone: '0984000003',
    dateOfBirth: '03/01/1996',
    sex: 'Nam',
    department: 'Back Office',
    employeeType: 'Quản lý',
    jobTitle: 'Trưởng phòng hành chính - nhân sự',
    salary: '9000000',
    dateStarted: '03/01/2018',
    workType: 'Full-Time',
    branch: 'Cơ sở Nguyễn Tuân',
    currentAddress: 'Số 47, Quan Nhân, Thanh Xuân, Hà Nội',
    permanentAddress: 'Thanh Thuỷ, Thanh Hà, Hải Dương',
    nationalId: '142700000',
    licenseDate: '03/01/2016',
    licensePlace: 'CA Hải Dương',
  },
  {
    id: '4',
    code: 'MNV-004',
    firstName: 'Nguyễn	Văn',
    lastName: 'A',
    personalEmail: 'nguyenvana01@gmail.com',
    workEmail: 'a.nguyen@base.vn',
    phone: '0984000004',
    dateOfBirth: '04/01/1996',
    sex: 'Nam',
    department: 'BOD',
    employeeType: 'BOD',
    jobTitle: 'Phó giám đốc khối nghiệp vụ',
    salary: '9000000',
    dateStarted: '04/01/2018',
    workType: 'Full-Time',
    branch: 'Cơ sở Nguyễn Tuân',
    currentAddress: 'Số 47, Quan Nhân, Thanh Xuân, Hà Nội',
    permanentAddress: 'Thanh Thuỷ, Thanh Hà, Hải Dương',
    nationalId: '142700000',
    licenseDate: '04/01/2016',
    licensePlace: 'CA Hải Dương',
  },
  {
    id: '5',
    code: 'MNV-005',
    firstName: 'Nguyễn	Văn',
    lastName: 'A',
    personalEmail: 'nguyenvana01@gmail.com',
    workEmail: 'a.nguyen@base.vn',
    phone: '0984000005',
    dateOfBirth: '05/01/1996',
    sex: 'Nam',
    department: 'BOD',
    employeeType: 'BOD',
    jobTitle: 'Phó giám đốc khối trường học',
    salary: '9000000',
    dateStarted: '05/01/2018',
    workType: 'Full-Time',
    branch: 'Cơ sở Nguyễn Tuân',
    currentAddress: 'Số 47, Quan Nhân, Thanh Xuân, Hà Nội',
    permanentAddress: 'Thanh Thuỷ, Thanh Hà, Hải Dương',
    nationalId: '142700000',
    licenseDate: '05/01/2016',
    licensePlace: 'CA Hải Dương',
  },
  {
    id: '6',
    code: 'MNV-006',
    firstName: 'Nguyễn	Văn',
    lastName: 'A',
    personalEmail: 'nguyenvana01@gmail.com',
    workEmail: 'a.nguyen@base.vn',
    phone: '0984000006',
    dateOfBirth: '06/01/1996',
    sex: 'Nam',
    department: 'Back Office',
    employeeType: 'Nhân viên',
    jobTitle: 'Chuyên viên tuyển dụng',
    salary: '9000000',
    dateStarted: '06/01/2018',
    workType: 'Full-Time',
    branch: 'Cơ sở Nguyễn Tuân',
    currentAddress: 'Số 47, Quan Nhân, Thanh Xuân, Hà Nội',
    permanentAddress: 'Thanh Thuỷ, Thanh Hà, Hải Dương',
    nationalId: '142700000',
    licenseDate: '06/01/2016',
    licensePlace: 'CA Hải Dương',
  },
  {
    id: '7',
    code: 'MNV-007',
    firstName: 'Nguyễn	Văn',
    lastName: 'A',
    personalEmail: 'nguyenvana01@gmail.com',
    workEmail: 'a.nguyen@base.vn',
    phone: '0984000007',
    dateOfBirth: '07/01/1996',
    sex: 'Nam',
    department: 'Back Office',
    employeeType: 'Nhân viên',
    jobTitle: 'Chuyên viên C&B',
    salary: '9000000',
    dateStarted: '07/01/2018',
    workType: 'Full-Time',
    branch: 'Cơ sở Nguyễn Tuân',
    currentAddress: 'Số 47, Quan Nhân, Thanh Xuân, Hà Nội',
    permanentAddress: 'Thanh Thuỷ, Thanh Hà, Hải Dương',
    nationalId: '142700000',
    licenseDate: '07/01/2016',
    licensePlace: 'CA Hải Dương',
  },
  {
    id: '8',
    code: 'MNV-008',
    firstName: 'Nguyễn	Văn',
    lastName: 'A',
    personalEmail: 'nguyenvana01@gmail.com',
    workEmail: 'a.nguyen@base.vn',
    phone: '0984000008',
    dateOfBirth: '08/01/1996',
    sex: 'Nam',
    department: 'Back Office',
    employeeType: 'Nhân viên',
    jobTitle: 'Admin',
    salary: '9000000',
    dateStarted: '08/01/2018',
    workType: 'Full-Time',
    branch: 'Cơ sở Nguyễn Tuân',
    currentAddress: 'Số 47, Quan Nhân, Thanh Xuân, Hà Nội',
    permanentAddress: 'Thanh Thuỷ, Thanh Hà, Hải Dương',
    nationalId: '142700000',
    licenseDate: '08/01/2016',
    licensePlace: 'CA Hải Dương',
  },
];
